services:
  firstservice:
    build: ./clienteMqtt/
    container_name: firstcontainer
    environment:
      - direccionbroker=fiounam.duckdns.org
      - topicoS=festichola
      - topicoS1=after
      - topicoP=contadorAI
    restart: always